#!/usr/bin/python3

'''
---------USAGE --------------

python3 login_network username password

T

'This is spoorthy

'''

import requests

url = 'http://192.168.50.1:8090/httpclient.html'

import sys

payload = {'mode' : '191', 'username' : sys.argv[1], 'password' : sys.argv[2] }


response = requests.post(url, payload).content.decode()


if 'You are signed in as'  in response:
    print("logged In")
else:
    print('Gone Wrong')

